services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: open-webui:v0.5.4
    # Uncomment if you prefer a pre-built image instead of building locally
    # image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
      - qdrant
      - docling
      - playwright
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
      - api-dev.tikehaucapital.com:192.168.10.53
    dns:
      - 192.168.10.10
      - 8.8.8.8
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    env_file:
      - .env
    command: "http open-webui:8080 --domain=${NGROK_DOMAIN}"
    ports:
      - "4040:4040"
    depends_on:
      - open-webui
    restart: unless-stopped

  tika:
    image: apache/tika:${TIKA_VERSION-2.9.1.0}
    container_name: tika
    restart: unless-stopped
    ports:
      - ${TIKA_PORT-9998}:9998
    healthcheck:
      test: ["CMD", "curl", "-f", "${TIKA_SERVER_ENDPOINT}/tika"]
      interval: ${TIKA_HEALTHCHECK_INTERVAL-30s}
      timeout: ${TIKA_HEALTHCHECK_TIMEOUT-10s}
      retries: ${TIKA_HEALTHCHECK_RETRIES-3}

  docling:
    image: quay.io/docling-project/docling-serve:${DOCLING_VERSION-latest}
    container_name: docling
    restart: unless-stopped
    ports:
      - ${DOCLING_PORT-5001}:5001
    environment:
      - DOCLING_SERVE_ENABLE_UI=${DOCLING_SERVE_ENABLE_UI-true}
      - DOCLING_OCR_ENGINE=${DOCLING_OCR_ENGINE-tesseract}
      - DOCLING_OCR_LANGUAGES=${DOCLING_OCR_LANGUAGES-eng}
    healthcheck:
      test: ["CMD", "curl", "-f", "${DOCLING_SERVER_ENDPOINT}/health"]
      interval: ${DOCLING_HEALTHCHECK_INTERVAL-30s}
      timeout: ${DOCLING_HEALTHCHECK_TIMEOUT-10s}
      retries: ${DOCLING_HEALTHCHECK_RETRIES-3}

  playwright:
    image: mcr.microsoft.com/playwright:v1.49.1-noble
    container_name: playwright
    command: npx -y playwright@1.49.1 run-server --port 3000 --host 0.0.0.0
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
  qdrant_data: {}